### ISSUE TITLE
Broadcast data to Xdrip

### ISSUE THREAD

**Issue by WalkingMyRoad** [NightscoutFoundation/xDrip#1058]
Dear developer,
can i send data to xDrip like AndroidAps ? if i can, How should i do?
Thank you very much for your recovery.

more
If you are interested in learning about us, please contact me at gitter.I tried to contact you, but I didn't get a response, Or please give me an email to contact you.

**Comment by MasterPlexus** [comment]
This is dependent on several things. 
- Wich data you want to send (is it something new, or established known datafileds)?
- from.where this want to be transfered

Generally you can produce intends to transfer data to a other app. Normally this must be implemented on sender app and receiver app. And booth apps should know that there is an allowed receiver... So without any further information it is not easy to give a suggestion, as also other ways of transferring of data is possible (web pull, Export Import and so.on)...

**Comment by WalkingMyRoad** [comment]
Sorry, I didn't elaborate completely.
we are CGM company named POCTech Co.,Ltd. ,Similar to Dexcome. We already have our own sensors and app named POCTech Care Mobile in googleplay store. we want send our glucose data to xDrip via Broadcast . 
We have successfully passed the data to Androidaps. we also want to do this in xDrip.
Sorry for the slow response due to the time zone problem

**Comment by WalkingMyRoad** [comment]
Sorry, I didn't elaborate completely.
we are CGM company named POCTech Co.,Ltd. ,Similar to Dexcome. We already have our own sensors and app named POCTech Care Mobile in googleplay store. we want send our glucose data to xDrip via Broadcast .
We have successfully passed the data to Androidaps. we also want to do this in xDrip.
Sorry for the slow response due to the time zone problem


> This is dependent on several things.
> 
> * Wich data you want to send (is it something new, or established known datafileds)?
> * from.where this want to be transfered
> 
> Generally you can produce intends to transfer data to a other app. Normally this must be implemented on sender app and receiver app. And booth apps should know that there is an allowed receiver... So without any further information it is not easy to give a suggestion, as also other ways of transferring of data is possible (web pull, Export Import and so.on)...

Sorry, I didn't elaborate completely.
we are CGM company named POCTech Co.,Ltd. ,Similar to Dexcome. We already have our own sensors and app named POCTech Care Mobile in googleplay store. we want send our glucose data to xDrip via Broadcast .
We have successfully passed the data to Androidaps. we also want to do this in xDrip.
Sorry for the slow response due to the time zone problem

**Comment by MasterPlexus** [comment]
Normally this should not be not a big problem. But it will be better to place it as an extra intend to xdrip imo, so it is clear selectable for the receiver.

Normally the best is, if someone who has also one or more of your sensors, and some experiences in coding, to implement it in xdrip, or as Xdrip is open source, so it is open to you to give a pull request for implementing the processing of the data receiving from your app. 

Under the line I see not that this will not be possible, but at the end @jamorham has to decide when a pull request comes up...

**Comment by WalkingMyRoad** [comment]
> Normally this should not be not a big problem. But it will be better to place it as an extra intend to xdrip imo, so it is clear selectable for the receiver.
> 
> Normally the best is, if someone who has also one or more of your sensors, and some experiences in coding, to implement it in xdrip, or as Xdrip is open source, so it is open to you to give a pull request for implementing the processing of the data receiving from your app.
> 
> Under the line I see not that this will not be possible, but at the end @jamorham has to decide when a pull request comes up...

Thank you for your reply ,  i think implementting it in xdrip is very diffcult , so i want our app as an open souece in Hardware Data Source.
![Screenshot_20191021-152015_xDrip+](https://user-images.githubusercontent.com/12733707/67184706-e9c57300-f416-11e9-8182-4d4a365e82ce.jpg)

we do the same in AndroidAps.
![Screenshot_20191021-151340](https://user-images.githubusercontent.com/12733707/67184832-301ad200-f417-11e9-8d0a-4e3472648325.png)

I'm sorry I didn't leave a contact information last time
my email : simon.min@poctech.net 
I'm sorry that I can't reply immediately due to the time zone problem. If you are interested, please contact me. Our products have been used in Greece，We want to help more diabetics get a better experience. Thank you . @jamorham @MasterPlexus

**Comment by MasterPlexus** [comment]
@WalkingMyRoad That was what I mean. I did not stated to implement the hole connection to be implemented in xDrip. 
I see the implementation in AndroidAPS, and it looks like not that complex, but I'm not that deep in handling Intends.  But as far as I could see, you should add in your app als that the intends will be send to xdrip in addition (at the moment in your screenshot I see `intend.setPackage(packageNameAndroidaps);'`
and I'm not sure that xDrip could receive it, as it is not placed for it.

**Comment by tzachi-dar** [comment]
If you only want to send BG data as intents, you can do that, but the user will have to select things that are not related to your CGM. Are you sure it is a good thing to do?

If yes, I can point you on how to do it.

**Comment by WalkingMyRoad** [comment]
> If you only want to send BG data as intents, you can do that, but the user will have to select things that are not related to your CGM. Are you sure it is a good thing to do?
> 
> If yes, I can point you on how to do it.

Because we don't collect users' data to the cloud, but we need to give users a way to watch their children's blood sugar at home. Xdrip is the best choice. For now, we only want to send BG data as intents, but how to give xdrip compliant coding parameters , please give some Suggestions and examples.

**Comment by WalkingMyRoad** [comment]
> @WalkingMyRoad That was what I mean. I did not stated to implement the hole connection to be implemented in xDrip.
> I see the implementation in AndroidAPS, and it looks like not that complex, but I'm not that deep in handling Intends. But as far as I could see, you should add in your app als that the intends will be send to xdrip in addition (at the moment in your screenshot I see `intend.setPackage(packageNameAndroidaps);`
> and I'm not sure that xDrip could receive it, as it is not placed for it.

We designed a switch option to let users choose which application to transfer data to. every switch sets different package.
![Screenshot_20191022-093730](https://user-images.githubusercontent.com/12733707/67254493-e92ceb00-f4af-11e9-92e3-94d4ef098ebf.png)
Of course, we will add xdrip if the test passes.

**Comment by tzachi-dar** [comment]
Here is the way that the oop sends data back to xDrip:
https://github.com/tzachi-dar/LibreOOPAlgorithm/blob/8ac65ad064f19a1b259ddf18b6382bc74b61e2f0/app/src/main/java/com/hg4/oopalgorithm/oopalgorithm/IntentsReceiver.java#L120

You can send it on the same way.
For this to work, your users will have to configure xDrip according to
the following instructions:

1) Install xDrip
2) Choose libre as the sensor type.
3) Choose miaomiao
4) Go to settings->hw data source and choose libre wifi
5) Go to list of receivers and enter 127.0.0.1:5000
6) Start a new sensor (answer not today).
7) Go to settings->less common settings->other misc options-> and set "use
oop algorithm"

This configuration is far from being intuitive, but users will see the BG
and alerts will work and so on.

**Comment by WalkingMyRoad** [comment]
> This configuration is far from being intuitive, but users will see the BG and alerts will work and so on.

Hi tzachi-dar, I tried your suggestion.
some questions:
https://github.com/NightscoutFoundation/xDrip/blob/606e53c0f6a601627e78588441aa77660aa22f25/app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreOOPAlgorithm.java
logs follows:
11-04 15:56:05.342 10737-11937/? E/LibreOOPAlgorithm: HandleData called with {"oOPResultsArray":[{"currentBg":174,"currentTime":57,"currentTrend":0,"serialNumber":"","timestamp":1572854160000}],"version":1}
11-04 16:14:05.368 14031-14225/? E/AndroidRuntime: FATAL EXCEPTION: Thread-33
                                                   Process: com.eveningoutpost.dexdrip, PID: 14031
                                                   java.lang.NullPointerException: Attempt to get length of null array
                                                       at com.eveningoutpost.dexdrip.Models.LibreOOPAlgorithm.HandleData(LibreOOPAlgorithm.java:121)
                                                       at com.eveningoutpost.dexdrip.NSEmulatorReceiver$1.run(NSEmulatorReceiver.java:105)
I can't find the reason Because it's normal for me to try locally. @tzachi-dar

**Comment by emaragkos** [comment]
Hey there all!
@WalkingMyRoad are you planning to implement the connection between POCTech and xDrip?
Also do you have any documentation about connecting POCTech with Nightscout and Androidaps
Thank you :)

**Comment by Navid200** [comment]
@WalkingMyRoad   If the questions have not been answered, please update.

**Comment by Navid200** [comment]
You can post in the Gitter room.  The developers see the posts.
https://gitter.im/jamorham/xDrip-plus

**Comment by Navid200** [comment]
Closing due to inactivity
