### ISSUE TITLE
Database import does not complete successfully due to incorrect SQLite database corruption error

### ISSUE THREAD

**Issue by jwoglom** [NightscoutFoundation/xDrip#1475]
I ran into an issue today when re-installing the xDrip app and loading a previous database backup. It appears that the process of importing from a full database backup does not successfully complete.

From looking at `/data/user/0/com.eveningoutpost.dexdrip/databases` on the device's filesystem with `adb shell` and `run-as com.eveningoutpost.dexdrip`, it appears that the entire database file doesn't get copied over, as the size of the files in that directory don't end up reaching the full size of the original database import.

After I reload the app following the apparently-successful import, I see the following in adb logcat:

```
10-20 23:32:36.617 12403 12458 W SQLiteLog: (28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
10-20 23:32:36.617 12403 12458 W SQLiteLog: (28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
10-20 23:32:36.659 12403 12458 E SQLiteLog: (11) database corruption at line 66389 of [b2325a6e1c]
10-20 23:32:36.659 12403 12458 E SQLiteLog: (11) database disk image is malformed in "PRAGMA journal_mode"
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: Database corruption detected in open()
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT): , while compiling: PRAGMA journal_mode
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:788)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:405)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:345)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:258)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.activeandroid.Cache.openDatabase(Cache.java:106)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.activeandroid.Cache.initialize(Cache.java:75)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.Models.JoH.fullDatabaseReset(JoH.java:822)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.utils.DatabaseUtil.loadSql(DatabaseUtil.java:392)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.ImportDatabaseActivity$LoadTask.doInBackground(ImportDatabaseActivity.java:360)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.ImportDatabaseActivity$LoadTask.doInBackground(ImportDatabaseActivity.java:266)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-20 23:32:36.724 12403 12458 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:923)
10-20 23:32:36.724 12403 12458 E DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: DB wipe detected: package=com.eveningoutpost.dexdrip reason=corruption file=/data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db ctime=2020-10-21T03:32:36Z mtime=2020-10-21T03:32:36Z atime=2020-10-21T03:32:35Z checkfile [unable to obtain timestamp]
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: java.lang.Throwable: STACKTRACE
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.wipeDetected(SQLiteDatabase.java:2855)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.DefaultDatabaseErrorHandler.onCorruption(DefaultDatabaseErrorHandler.java:55)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.onCorruption(SQLiteDatabase.java:402)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:902)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.activeandroid.Cache.openDatabase(Cache.java:106)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.activeandroid.Cache.initialize(Cache.java:75)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:44)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:34)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.activeandroid.ActiveAndroid.initialize(ActiveAndroid.java:30)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.Models.JoH.fullDatabaseReset(JoH.java:822)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.utils.DatabaseUtil.loadSql(DatabaseUtil.java:392)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.ImportDatabaseActivity$LoadTask.doInBackground(ImportDatabaseActivity.java:360)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at com.eveningoutpost.dexdrip.ImportDatabaseActivity$LoadTask.doInBackground(ImportDatabaseActivity.java:266)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-20 23:32:36.731 12403 12458 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:923)
10-20 23:32:36.732 12403 12458 E DefaultDatabaseErrorHandler: deleting the database file: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
```

Despite the apparent corruption error, the sqlite database file did not contain any actual corruption:
```
$ sqlite3 export20201020-223940.sqlite
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> PRAGMA integrity_check;
ok
```

Manually replacing `/data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db` with the file to be imported works fine, so I think there is an issue with the xDrip database import process. My database is quite large -- I have 2+ years of xDrip data contained in it -- so that might be related to why this issue is occurring.

**Comment by tolot27** [comment]
@jwoglom Please provide your full environment as described in the [bug report template](https://github.com/NightscoutFoundation/xDrip/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) including the available RAM and free disk space of your phone.

**Comment by Navid200** [comment]
Is the version of xDrip, importing, the same as the version of xDrip that exported the settings?

**Comment by Navid200** [comment]
Closing due to inactivity

**Comment by jwoglom** [comment]
Just wanted to belatedly mention -- I tested loading in a backup on the latest release for an unrelated reason and the error didn't occur. Will reply if I notice it again.

**Comment by jwoglom** [comment]
I noticed this issue again. The root cause appears to be
```
10-15 00:35:42.484 31312 31497 W SQLiteLog: (28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
10-15 00:35:42.485 31312 31497 W SQLiteLog: (28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
10-15 00:35:42.486 31312 31497 W SQLiteLog: (28) file unlinked while open: /data/user/0/com.eveningoutpost.dexdrip/databases/DexDrip.db
```

which appears because the database is closed _after_ renaming the imported backup to the sqlite database file, causing a race condition which seems to appear more frequently the larger the size of your database. I am opening a PR to resolve this issue.
