### ISSUE TITLE
Wear-Crash on settings change

### ISSUE THREAD

**Issue by AdrianLxM** [NightscoutFoundation/xDrip#167]
```
09-01 18:22:47.817 25782-25782/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.eveningoutpost.dexdrip, PID: 25782
                                                   java.lang.IllegalStateException: await must not be called on the UI thread when time is greater than zero.
                                                       at com.google.android.gms.common.internal.zzab.zza(Unknown Source)
                                                       at com.google.android.gms.internal.zzpo.await(Unknown Source)
                                                       at com.eveningoutpost.dexdrip.ListenerService.setLocalNodeName(ListenerService.java:2452)
                                                       at com.eveningoutpost.dexdrip.ListenerService.sendPrefSettings(ListenerService.java:668)
                                                       at com.eveningoutpost.dexdrip.ListenerService.access$2400(ListenerService.java:90)
                                                       at com.eveningoutpost.dexdrip.ListenerService$1.onSharedPreferenceChanged(ListenerService.java:850)
                                                       at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:479)
                                                       at android.app.SharedPreferencesImpl$EditorImpl.-wrap0(SharedPreferencesImpl.java)
                                                       at android.app.SharedPreferencesImpl$EditorImpl$3.run(SharedPreferencesImpl.java:487)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The commit introducing the issue seems to be this one:
https://github.com/NightscoutFoundation/xDrip/commit/93e9d3be2b74ab8099d42e6f4ebae1a6def38c95#diff-2fe96e74ad12748a3a7c51ce3bf38ccf

It does not like waiting on an UI-Thread:
`NodeApi.GetLocalNodeResult localnodes = Wearable.NodeApi.getLocalNode(googleApiClient).await(60, TimeUnit.SECONDS);`

I'm not sure if I enabled "force wear" from the phone or the watch.

**Comment by kskandispersonal** [comment]
I made the fix to setLocaleNode and it is working correctly.  Here's a snippet from the log...
```

**Comment by kskandispersonal** [comment]
```09-04 19:48:21.867 3857-3857/? D/jamorham listener: DataRequester DataRequester: /nightscout_watch_data_resend lastRequest:1969-12-31 19:00:00
09-04 19:48:21.879 3857-3913/? D/jamorham listener: doInBackground enter enable_wearG5=true force_wearG5=false node_wearG5=SmartWatch 3 B22E|8fdbed4e
09-04 19:48:21.900 3857-3857/? D/jamorham listener: getLocalNode Status=: SUCCESS
09-04 19:48:21.900 3857-3857/? D/jamorham listener: setLocalNodeName.  localnode=SmartWatch 3 2D74|a5d3f973
09-04 19:48:21.918 3857-3913/? D/jamorham listener: doInBackground connected.  CapabilityApi.GetCapabilityResult mPhoneNodeID=38b544c3 count=1 localnode=SmartWatch 3 2D74|a5d3f973
09-04 19:48:21.919 3857-3913/? D/jamorham listener: stopService call stopService
```

**Comment by jamorham** [comment]
For reference this should be corrected in the Sept 8th nightly
