### ISSUE TITLE
NPE on GATT

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#169]
```
09-05 21:26:52.700 29862-29862/com.eveningoutpost.dexdrip I/DexCollectionService: attemptConnection: Connection state: CONNECTED
09-05 21:26:52.700 29862-29862/com.eveningoutpost.dexdrip I/DexCollectionService: attemptConnection: Looks like we are already connected, ready to receive
09-05 21:26:54.140 29862-29886/com.eveningoutpost.dexdrip I/DexCollectionService: onConnectionStateChange: State disconnected.
09-05 21:26:54.180 29862-29886/com.eveningoutpost.dexdrip I/DexCollectionService: onConnectionStateChange: mBluetoothGatt is not null, closing.
09-05 21:26:54.200 29862-29886/com.eveningoutpost.dexdrip I/DexCollectionService: onConnectionStateChange: Disconnected from GATT server.
09-05 21:26:54.225 29862-29886/com.eveningoutpost.dexdrip W/BluetoothGatt: Unhandled exception in callback
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGattCallback.onConnectionStateChange(android.bluetooth.BluetoothGatt, int, int)' on a null object reference
                                                                               at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:181)
                                                                               at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
                                                                               at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by jamorham** [comment]
Should now be trapped by: https://github.com/NightscoutFoundation/xDrip/commit/05c51872b19c643eb5146e5c5d86844d03d4baf4

**Comment by gregorybel** [comment]
did not see it again since fix!

**Comment by jamorham** [comment]
I saw this again last night, further corrections are in the Sept 9th nightly. Please check that it still functions correctly.

**Comment by jamorham** [comment]
marking as resolved
