### ISSUE TITLE
Instant Crash without Play Services

### ISSUE THREAD

**Issue by moberer** [NightscoutFoundation/xDrip#2579]
### Instant Crash without Play Services
Link to the discussion thread:  https://github.com/NightscoutFoundation/xDrip/discussions/2578

### Your environment
- https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.09.08b or later
- no sensor connected
- GrapheneOS on Pixel 6a
- no Google Play services or Micro G

### Reproduction in Emulator

- latest master, build set to "app"
- Device: Pixel 5
- Image: 
  - Release Name: S
  - API 31
  - ABI x86_64, 
  - Android 12.0 (Important: The version **without** "(Google APIs ATD)" or "(Google APIs)"
- Just press "run". - The emulator will start and then quickly stop. - Look at the logs for details.

### Expected behavior
When opening the app, the app should open and stay open.

### Actual behavior
The app flashes up for a short moment (0.5 sec) and then instantly crashes.

When doing this repeatedly, I can get android to give me a backtrace:
```
type: crash
osVersion: google/bluejay/bluejay:13/TQ1A.221205.011/2022122000:user/release-keys
package: com.eveningoutpost.dexdrip:1603091400
process: com.eveningoutpost.dexdrip
processUptime: 475 + 189 ms

java.lang.RuntimeException: Unable to create service com.google.android.gms.measurement.AppMeasurementService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/~~eysawNWmQ4hJYEcbeJV8Dw==/com.eveningoutpost.dexdrip-R3zFO1xYfLPEK29EI55vNw==/base.apk"],nativeLibraryDirectories=[/data/app/~~eysawNWmQ4hJYEcbeJV8Dw==/com.eveningoutpost.dexdrip-R3zFO1xYfLPEK29EI55vNw==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4504)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/~~eysawNWmQ4hJYEcbeJV8Dw==/com.eveningoutpost.dexdrip-R3zFO1xYfLPEK29EI55vNw==/base.apk"],nativeLibraryDirectories=[/data/app/~~eysawNWmQ4hJYEcbeJV8Dw==/com.eveningoutpost.dexdrip-R3zFO1xYfLPEK29EI55vNw==/lib/arm64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4472)
	... 11 more

```

### Steps to reproduce the behavior:
0. Ensure environment is as described.
1. Tap app icon on home screen.

### Affected Versions
The problem affects https://github.com/NightscoutFoundation/xDrip/releases/tag/2022.09.08b and later.
This means the error was introduced here https://github.com/NightscoutFoundation/xDrip/compare/2022.09.08...2022.09.08b

Unfortunately, that is a bit of a big commit.

### Pointers and Possible Reasons
- com.google.android.gms.measurement.AppMeasurementService is usually pulled in indirectly by Firebase: In the diff some Firebase-related things were changed. - This is probably worth a closer look.
- From what I've seen with similar issues online: It is likely related to a change in the build files, not the actual code.

**Comment by moberer** [comment]
Full crash log in Emulator Environment:

```
12/24 10:51:35: Launching 'app' on Pixel 5 API 31.
Install successfully finished in 1 s 37 ms.
$ adb shell am start -n "com.eveningoutpost.dexdrip/com.eveningoutpost.dexdrip.Home" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 1740 on device 'Pixel_5_API_31 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/outpost.dexdri: Late-enabling -Xcheck:jni
W/outpost.dexdri: Unexpected CPU variant for X86 using defaults: x86_64
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10105; state: DISABLED
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
V/GraphicsEnvironment: ANGLE Developer option for 'com.eveningoutpost.dexdrip' set to: 'default'
V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: Installing application
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
W/ComponentDiscovery: Application info not found.
W/ComponentDiscovery: Could not retrieve metadata, returning empty list of registrars.
D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
E/FirebaseInstanceId: Google Play services missing or without correct permission.
I/FirebaseInitProvider: FirebaseApp initialization successful
D/CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10105; state: DISABLED
I/FA: App measurement is starting up, version: 12451
I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.eveningoutpost.dexdrip
E/FA: AppMeasurementService not registered/enabled
E/FA: Uploading is not possible. App measurement disabled
D/Inevitable: Creating task: Register-start due: 2022-12-24 10:51:56
D/Inevitable: Creating task: Commit-start due: 2022-12-24 10:51:51
E/SQLiteLog: (1) duplicate column name: dg_mgdl in "ALTER TABLE BgReadings ADD COLUMN dg_mgdl REAL;"
E/SQLiteLog: (1) duplicate column name: dg_slope in "ALTER TABLE BgReadings ADD COLUMN dg_slope REAL;"
E/SQLiteLog: (1) duplicate column name: dg_delta_name in "ALTER TABLE BgReadings ADD COLUMN dg_delta_name TEXT;"
E/SQLiteLog: (1) duplicate column name: source_info in "ALTER TABLE BgReadings ADD COLUMN source_info TEXT;"
E/SQLiteLog: (1) table LibreBlock already exists in "CREATE TABLE LibreBlock (_id INTEGER PRIMARY KEY AUTOINCREMENT);"
E/SQLiteLog: (1) duplicate column name: timestamp in "ALTER TABLE LibreBlock ADD COLUMN timestamp INTEGER;"
E/SQLiteLog: (1) duplicate column name: reference in "ALTER TABLE LibreBlock ADD COLUMN reference TEXT;"
E/SQLiteLog: (1) duplicate column name: blockbytes in "ALTER TABLE LibreBlock ADD COLUMN blockbytes BLOB;"
E/SQLiteLog: (1) duplicate column name: bytestart in "ALTER TABLE LibreBlock ADD COLUMN bytestart INTEGER;"
E/SQLiteLog: (1) duplicate column name: byteend in "ALTER TABLE LibreBlock ADD COLUMN byteend INTEGER;"
E/SQLiteLog: (1) duplicate column name: calculatedbg in "ALTER TABLE LibreBlock ADD COLUMN calculatedbg REAL;"
E/SQLiteLog: (1) duplicate column name: uuid in "ALTER TABLE LibreBlock ADD COLUMN uuid TEXT;"
E/SQLiteLog: (1) duplicate column name: patchUid in "ALTER TABLE LibreBlock ADD COLUMN patchUid BLOB;"
E/SQLiteLog: (1) duplicate column name: patchInfo in "ALTER TABLE LibreBlock ADD COLUMN patchInfo BLOB;"
E/SQLiteLog: (1) index index_LibreBlock_timestamp already exists in "CREATE INDEX index_LibreBlock_timestamp on LibreBlock(timestamp);"
E/SQLiteLog: (1) index index_LibreBlock_bytestart already exists in "CREATE INDEX index_LibreBlock_bytestart on LibreBlock(bytestart);"
E/SQLiteLog: (1) index index_LibreBlock_byteend already exists in "CREATE INDEX index_LibreBlock_byteend on LibreBlock(byteend);"
E/SQLiteLog: (1) index index_LibreBlock_uuid already exists in "CREATE INDEX index_LibreBlock_uuid on LibreBlock(uuid);"
E/SQLiteLog: (1) table LibreData already exists in "CREATE TABLE LibreData (_id INTEGER PRIMARY KEY AUTOINCREMENT);"
E/SQLiteLog: (1) duplicate column name: timestamp in "ALTER TABLE LibreData ADD COLUMN timestamp INTEGER;"
E/SQLiteLog: (1) duplicate column name: temperature in "ALTER TABLE LibreData ADD COLUMN temperature REAL;"
E/SQLiteLog: (1) duplicate column name: temperatureraw in "ALTER TABLE LibreData ADD COLUMN temperatureraw INTEGER;"
E/SQLiteLog: (1) index index_LibreData_timestamp already exists in "CREATE INDEX index_LibreData_timestamp on LibreData(timestamp);"
E/SQLiteLog: (1) table APStatus already exists in "CREATE TABLE APStatus (_id INTEGER PRIMARY KEY AUTOINCREMENT);"
E/SQLiteLog: (1) duplicate column name: timestamp in "ALTER TABLE APStatus ADD COLUMN timestamp INTEGER;"
E/SQLiteLog: (1) duplicate column name: basal_percent in "ALTER TABLE APStatus ADD COLUMN basal_percent INTEGER;"
E/SQLiteLog: (1) duplicate column name: basal_absolute in "ALTER TABLE APStatus ADD COLUMN basal_absolute REAL default -1;"
E/SQLiteLog: (1) table Prediction already exists in "CREATE TABLE Prediction (_id INTEGER PRIMARY KEY AUTOINCREMENT);"
E/SQLiteLog: (1) duplicate column name: timestamp in "ALTER TABLE Prediction ADD COLUMN timestamp INTEGER;"
E/SQLiteLog: (1) duplicate column name: glucose in "ALTER TABLE Prediction ADD COLUMN glucose REAL;"
E/SQLiteLog: (1) duplicate column name: source in "ALTER TABLE Prediction ADD COLUMN source TEXT;"
E/SQLiteLog: (1) duplicate column name: note in "ALTER TABLE Prediction ADD COLUMN note TEXT;"
E/SQLiteLog: (1) table DesertSync already exists in "CREATE TABLE DesertSync (_id INTEGER PRIMARY KEY AUTOINCREMENT);"
E/SQLiteLog: (1) duplicate column name: timestamp in "ALTER TABLE DesertSync ADD COLUMN timestamp INTEGER;"
E/SQLiteLog: (1) duplicate column name: topic in "ALTER TABLE DesertSync ADD COLUMN topic TEXT;"
E/SQLiteLog: (1) duplicate column name: sender in "ALTER TABLE DesertSync ADD COLUMN sender TEXT;"
E/SQLiteLog: (1) duplicate column name: payload in "ALTER TABLE DesertSync ADD COLUMN payload TEXT;"
E/SQLiteLog: (1) duplicate column name: processed in "ALTER TABLE DesertSync ADD COLUMN processed TEXT;"
E/SQLiteLog: (1) table PenData already exists in "CREATE TABLE PenData (_id INTEGER PRIMARY KEY AUTOINCREMENT, battery INTEGER, created_timestamp INTEGER, flags INTEGER, idx INTEGER, pen_mac TEXT, raw BLOB, temperature REAL, t
E/SQLiteLog: (1) duplicate column name: bitmap in "ALTER TABLE PenData ADD COLUMN bitmap INTEGER;"
E/SQLiteLog: (1) duplicate column name: insulin_name in "ALTER TABLE PenData ADD COLUMN insulin_name TEXT;"
E/SQLiteLog: (1) index index_PenData_pen_mac already exists in "CREATE INDEX index_PenData_pen_mac on PenData(pen_mac);"
E/SQLiteLog: (1) index index_PenData_typ already exists in "CREATE INDEX index_PenData_typ on PenData(typ);"
E/SQLiteLog: (1) no such table: Libre2RawValue in "DROP TABLE Libre2RawValue;"
E/SQLiteLog: (1) table Libre2RawValue2 already exists in "CREATE TABLE Libre2RawValue2 (_id INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER, serial STRING, glucose REAL);"
E/SQLiteLog: (1) index index_Libre2RawValue2_ts already exists in "CREATE INDEX index_Libre2RawValue2_ts on Libre2RawValue2(ts);"
E/SQLiteLog: (1) table Libre2Sensors already exists in "CREATE VIEW Libre2Sensors AS SELECT MIN(_id) as _id, serial, MIN(ts) as ts_from, MAX(ts) AS ts_to, COUNT(*) AS readings FROM Libre2RawValue2 GROUP BY serial ORDER BY ts D
E/SQLiteLog: (1) duplicate column name: volume in "ALTER TABLE AlertType ADD COLUMN volume INTEGER;"
E/SQLiteLog: (1) duplicate column name: light in "ALTER TABLE AlertType ADD COLUMN light INTEGER;"
E/SQLiteLog: (1) duplicate column name: predictive in "ALTER TABLE AlertType ADD COLUMN predictive INTEGER;"
E/SQLiteLog: (1) duplicate column name: text in "ALTER TABLE AlertType ADD COLUMN text TEXT;"
E/SQLiteLog: (1) duplicate column name: force_speaker in "ALTER TABLE AlertType ADD COLUMN force_speaker INTEGER;"
E/SQLiteLog: (1) duplicate column name: time_until_threshold_crossed in "ALTER TABLE AlertType ADD COLUMN time_until_threshold_crossed REAL;"
E/SQLiteLog: (1) duplicate column name: bg_unclear_readings_alert in "ALTER TABLE Notifications ADD COLUMN bg_unclear_readings_alert INTEGER;"
E/SQLiteLog: (1) duplicate column name: bg_missed_alerts in "ALTER TABLE Notifications ADD COLUMN bg_missed_alerts INTEGER;"
E/SQLiteLog: (1) duplicate column name: bg_rise_alert in "ALTER TABLE Notifications ADD COLUMN bg_rise_alert INTEGER;"
E/SQLiteLog: (1) duplicate column name: bg_fall_alert in "ALTER TABLE Notifications ADD COLUMN bg_fall_alert INTEGER;"
I/CompatibleApps: Enabling default workarounds for Android 10+ setting minimize/avoid scanning to enabled
I/xDrip-Daily: 2022-12-24 10:51:51 Job Scheduled
I/GcmAvailableHelper: GCM service enabled
W/GooglePlayServicesUtil: Google Play Store is missing.
D/JobProxy26: Schedule periodic jobInfo success, request{id=1, tag=xDrip-Daily, transient=false}, interval 00:00:00 (+1 day), flex 12:00:00
D/Inevitable: Creating task: launch-missed-readings due: 2022-12-24 10:51:52
D/NFCReaderX: HomeScreen Scan State: disable
I/Notifications: read saved_alerts string and it is empty
D/CollectionServiceStarter: restartCollectionServiceBackground Restart no args
D/Inevitable: Creating task: restart-collection-service due: 2022-12-24 10:51:51
D/jamorham plussync: Starting jamorham xDrip-Plus sync service: xdrip.java
I/VersionTracker: xDrip software version changed from:  to 5ea552c6f-2022.12.24-dev-debug
E/SQLiteLog: (1) table Reminder already exists in "CREATE TABLE Reminder (_id INTEGER PRIMARY KEY AUTOINCREMENT)"
E/SQLiteLog: (1) duplicate column name: next_due in "ALTER TABLE Reminder ADD COLUMN next_due INTEGER"
E/SQLiteLog: (1) duplicate column name: period in "ALTER TABLE Reminder ADD COLUMN period INTEGER"
E/SQLiteLog: (1) duplicate column name: snoozed_till in "ALTER TABLE Reminder ADD COLUMN snoozed_till INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: last_snoozed_for in "ALTER TABLE Reminder ADD COLUMN last_snoozed_for INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: last_fired in "ALTER TABLE Reminder ADD COLUMN last_fired INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: fired_times in "ALTER TABLE Reminder ADD COLUMN fired_times INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: alerted_times in "ALTER TABLE Reminder ADD COLUMN alerted_times INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: title in "ALTER TABLE Reminder ADD COLUMN title TEXT"
E/SQLiteLog: (1) duplicate column name: alt_title in "ALTER TABLE Reminder ADD COLUMN alt_title TEXT"
E/SQLiteLog: (1) duplicate column name: sound_uri in "ALTER TABLE Reminder ADD COLUMN sound_uri TEXT"
E/SQLiteLog: (1) duplicate column name: ideal_time in "ALTER TABLE Reminder ADD COLUMN ideal_time TEXT"
E/SQLiteLog: (1) duplicate column name: priority in "ALTER TABLE Reminder ADD COLUMN priority INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: enabled in "ALTER TABLE Reminder ADD COLUMN enabled INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: weekdays in "ALTER TABLE Reminder ADD COLUMN weekdays INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: weekends in "ALTER TABLE Reminder ADD COLUMN weekends INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: repeating in "ALTER TABLE Reminder ADD COLUMN repeating INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: alternating in "ALTER TABLE Reminder ADD COLUMN alternating INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: alternate in "ALTER TABLE Reminder ADD COLUMN alternate INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: chime in "ALTER TABLE Reminder ADD COLUMN chime INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: homeonly in "ALTER TABLE Reminder ADD COLUMN homeonly INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: speak in "ALTER TABLE Reminder ADD COLUMN speak INTEGER DEFAULT 0"
E/SQLiteLog: (1) duplicate column name: graphicon in "ALTER TABLE Reminder ADD COLUMN graphicon INTEGER DEFAULT 0"
E/SQLiteLog: (1) index index_Reminder_next_due already exists in "CREATE INDEX index_Reminder_next_due on Reminder(next_due)"
E/SQLiteLog: (1) index index_Reminder_enabled already exists in "CREATE INDEX index_Reminder_enabled on Reminder(enabled)"
E/SQLiteLog: (1) index index_Reminder_weekdays already exists in "CREATE INDEX index_Reminder_weekdays on Reminder(weekdays)"
E/SQLiteLog: (1) index index_Reminder_homeonly already exists in "CREATE INDEX index_Reminder_homeonly on Reminder(homeonly)"
E/SQLiteLog: (1) index index_Reminder_weekends already exists in "CREATE INDEX index_Reminder_weekends on Reminder(weekends)"
E/SQLiteLog: (1) no such column: timestamp in "CREATE INDEX index_Reminder_timestamp on Reminder(timestamp)"
E/SQLiteLog: (1) index index_Reminder_snoozed_till already exists in "CREATE INDEX index_Reminder_snoozed_till on Reminder(snoozed_till)"
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
D/NanoStatus: reflection exception: java.lang.NoSuchMethodException: com.eveningoutpost.dexdrip.services.DexCollectionService.nanoStatus [] DexCollectionService
D/NanoStatus: startRefresh
D/NanoStatus: startRefresh
D/Inevitable: Executing task! Commit-start
D/CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10105; state: ENABLED
W/outpost.dexdri: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/outpost.dexdri: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/xdrip-Experience: Looks like a Newbie
D/jamorham Home: INSULINSET: 0 3 3
D/jamorham Home: INSULINSET: 1 3 3
D/jamorham Home: INSULINSET: 2 3 3
D/jamorham Home: Initialize Search words
D/jamorham Home: Loaded Words: 10
D/InsulinManager: Initialize insulin profiles
D/InsulinManager: checking for uniqueness
D/InsulinManager: pharmacy product numbers uniquee
D/InsulinManager: initialized linear trapezoid insulin FIASP (ultra fast acting)
D/InsulinManager: initialized linear trapezoid insulin Novorapid (rapid acting)
D/InsulinManager: initialized linear trapezoid insulin Humalog (rapid acting)
D/InsulinManager: initialized linear trapezoid insulin Actrapid (short acting)
D/InsulinManager: initialized linear trapezoid insulin Insulatard (NPH)
D/InsulinManager: initialized linear trapezoid insulin Toujeo (long acting)
D/InsulinManager: initialized linear trapezoid insulin Lantus (long acting)
D/InsulinManager: Loaded Insulin Profiles: 7
D/InsulinManager: Loaded disabled Insulin Profiles from Prefs: []
D/InsulinManager: Loaded basal Insulin Profiles from Prefs: 
D/InsulinManager: Loaded bolus Insulin Profiles from Prefs: 
D/InsulinManager: InsulinManager initialized from config file and Prefs
D/jamorham Home: Width height: 1080 2148 DPI:440
D/jamorham Home: Processing incoming bundle
D/jamorham plussync: Starting jamorham xDrip-Plus sync service: HomeOnCreate
I/jamorham plussync: jamorham xDrip-Plus sync service onStart command called
I/jamorham plussync: jamorham xDrip-Plus sync service onStart command complete
I/jamorham plussync: jamorham xDrip-Plus sync service onStart command called
I/jamorham plussync: jamorham xDrip-Plus sync service onStart command complete
W/GooglePlayServicesUtil: Google Play Store is missing.
W/FA: Service invalid
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eveningoutpost.dexdrip, PID: 1740
    java.lang.RuntimeException: Unable to create service com.google.android.gms.measurement.AppMeasurementService: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/~~Ryo2iC9vyLvr8wu_N0pScQ==/com.eveningoutpost.dexdrip-1JKHPi3qt_YBynqVFbQGsw==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ryo2iC9vyLvr8wu_N0pScQ==/com.eveningoutpost.dexdrip-1JKHPi3qt_YBynqVFbQGsw==/lib/x86_64, /system/lib64, /system_ext/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
        at android.app.ActivityThread.access$1700(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurementService" on path: DexPathList[[zip file "/data/app/~~Ryo2iC9vyLvr8wu_N0pScQ==/com.eveningoutpost.dexdrip-1JKHPi3qt_YBynqVFbQGsw==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ryo2iC9vyLvr8wu_N0pScQ==/com.eveningoutpost.dexdrip-1JKHPi3qt_YBynqVFbQGsw==/lib/x86_64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4469)
        at android.app.ActivityThread.access$1700(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
I/FA: Tag Manager is not found and thus will not be used
D/Inevitable: Executing task! restart-collection-service
D/CollectionServiceStarter: queueRestart called
D/CollectionServiceStarter: Aquiring lock
D/CollectionServiceStarter: before: Stop Pending: false  Start Pending: false
D/CollectionServiceStarter:  after: Stop Pending: true  Start Pending: true
D/Inevitable: Creating task: collect-automata due: 2022-12-24 10:51:52
D/Inevitable: Executing task! launch-missed-readings
D/Inevitable: Executing task! collect-automata
D/CollectionServiceStarter: processPending: Issuing a stop all
D/CollectionServiceStarter: stop all
D/CollectionServiceStarter: stopping bt share service
D/Inevitable: Executing task! Register-start
```

**Comment by jamorham** [comment]
Thanks. I strongly suspect the cause will be due to a bug in the updated google play libraries (which is why we try to avoid updating them)

**Comment by jamorham** [comment]
Please try the Dec 24th nightly (available now) and see if this resolves the issue. Thanks for a comprehensive bug report and differential testing.

**Comment by moberer** [comment]
The Dec 24 nightly works!

No problem, thanks a lot for your time and effort and a very merry christmas!

**Comment by jamorham** [comment]
No problem. you too.
