### ISSUE TITLE
What should we do when parseInt in EditAlertActivity returns null

### ISSUE THREAD

**Issue by jamorham** [NightscoutFoundation/xDrip#40]
See example line here, the result is cast to `int` but can be null. There are a few places this occurs. What should we do with those to fail through cleanly when for whatever reason there could be invalid data?

Can we use `Integer` instead and test for null. What is the correct way to exit the `onTouch` listener when this might happen?

https://github.com/NightscoutFoundation/xDrip/blob/a3f32d9b3e760fc69b0ce3f9a7df57d0cd333ce4/app/src/main/java/com/eveningoutpost/dexdrip/EditAlertActivity.java#L795

**Comment by AdrianLxM** [comment]
Using `Integer` instead of `int` has other implications as well.

* `int` is always initialised; `Integer` are not.
* `int` are passed by value; `Integer` by reference. This can have the implication that if you pass an `Integer` to a function it might have side effects on the calling function if it modifies the value.
 * All `==`, `!=`, ... comparisons have to be changed to `a.equals(b)`, .... As with primitive datatypes they compare values but with non-primitive ones it compares references.

**Comment by jamorham** [comment]
Is `Integer` immutable if set `final` ?  In the cases I've seen in `EditAlertActivity` it is almost immediately cast to `int` like for example when being used as parameter for `SnoozeActivity.SetSnoozePickerValues`

If the pass by reference is a problem we could just evaluate it twice and do the null check or should we be passing up the `NullPointerException` instead and having `parseInt` return `int` instead of `Integer` ?

**Comment by tzachi-dar** [comment]
I'm not sure I understand how you can get a null there.
The behavior I see on my phone is that there is spiner that only allows one to get good values. (this are predefined values).

Assuming that you will soon answer how to reproduce this, than my suggestions:

1) block it from returning null.
2) if 1 is not possible than use the default value 
defaultSnooze = SnoozeActivity.getDefaultSnooze(above);

So, how do I reproduce this?

**Comment by AdrianLxM** [comment]
In this particular case

 * getInt() could either return a primitive Datatype with `0` as default, as in `SnoozeActivity.SetSnoozePickerValues()` and `SetSnoozePickerValues()` the "locatoin" (position?) will get set to a default value anyways. `alterReraiseInt` is also handled anyways to be not smaller than `1`. All other cases have to be handled either way.

* The other possibility is to use `Integer` and allow for `null` and simply handle that null case.

As the scope is limited, either way works.

**Comment by AdrianLxM** [comment]
@jamorham in general no;  setting a variable final means, the object it "points" to cannot be exchanged. But the values/state the Object holds can. In this case it effectively is like that as `Integer` has no methods to modify the content and by itself is a final Class so there cannot be subclasses.

**Comment by AdrianLxM** [comment]
And @tzachi-dar is right: the practical chance that a value is entered that cannot be parsed to an integer is close to zero. The input is either a spinner or limited to "number".

**Comment by jamorham** [comment]
I don't know a specific way to reproduce it, but android studio flags it as potential for null pointer exception and the frameworks on various phones can do strange things, for example some might allow local numeric symbols eg `,` to be entered in a number field and you can click to edit the spinner or the spinner view object might just fail to return correctly due to low memory conditions or losing focus etc.

I've raised the issue because I don't know enough about the flow of this code to simply wrap it with eg `if (xx == null) return false` for the rare occasions it might happen.

Here is a stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.eveningoutpost.dexdrip.EditAlertActivity$10.onTouch(EditAlertActivity.java:795)
       at android.view.View.dispatchTouchEvent(View.java:8383)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2431)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2120)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2782)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
       at android.view.View.dispatchPointerEvent(View.java:8579)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4028)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3894)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3585)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3483)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3642)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3509)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3475)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3483)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3456)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5708)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5682)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5653)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5798)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5219)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by tzachi-dar** [comment]
I would simply change the code from:
int defaultSnooze = parseInt(editSnooze.getText().toString());
to:
int defaultSnooze;
defaultSnoozeString = editSnooze.getText().toString();
if(defaultSnoozeString != null) {
   defaultSnooze = parseInt(defaultSnoozeString);
} else {
   defaultSnooze = SnoozeActivity.getDefaultSnooze(above);
}

Since this is only the default of how the dialog will start I guess that any solution will work...

**Comment by jamorham** [comment]
Although it could be caused by the String itself being null, if it is an invalid integer for some other reason then the nullpointer exception will come from the conversion of `Integer` to `int` which occurs on the referenced line. 

How about something very similar to that:

```
int defaultSnooze;
try {
      defaultSnooze = parseInt(editSnooze.getText().toString());
    } catch (NullPointerException e) {
      defaultSnooze = SnoozeActivity.getDefaultSnooze(above);
    }
```

**Comment by tzachi-dar** [comment]
Generally speaking, I don't like catching null pointer exceptions since this might hide bugs.
in this specific case it is ok, since we are only catching it from line (that actually have 3 functions).

**Comment by jamorham** [comment]
Yes I think the above is pretty safe but could also be done like:

```
Integer defaultSnooze = parseInt(editSnooze.getText().toString());
if (defaultSnooze == null)
                 defaultSnooze = SnoozeActivity.getDefaultSnooze(above);
```

I wrote it as above with the catch because then it doesn't change the type of `defaultSnooze` and there are a couple of other places which might need the same treatment.

Regardless of the implementation I think I've got an answer to the main question which is what to do when its null.

**Comment by jamorham** [comment]
Should now be resolved by: https://github.com/NightscoutFoundation/xDrip/commit/f4502664f76a2f3d4b1eec9fa101d23390908f1a
