### ISSUE TITLE
xdrip keeps crashing after playing with ip addresses and sending remote snooze.

### ISSUE THREAD

**Issue by tzachi-dar** [NightscoutFoundation/xDrip#612]
Not sure what happened first.

FATAL EXCEPTION: Thread-10127
E/AndroidRuntime( 9845): Process: com.eveningoutpost.dexdrip, PID: 9845
E/AndroidRuntime( 9845): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime( 9845): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
E/AndroidRuntime( 9845): 	at com.google.gson.Gson.fromJson(Gson.java:814)
E/AndroidRuntime( 9845): 	at com.google.gson.Gson.fromJson(Gson.java:779)
E/AndroidRuntime( 9845): 	at com.google.gson.Gson.fromJson(Gson.java:728)
E/AndroidRuntime( 9845): 	at com.google.gson.Gson.fromJson(Gson.java:700)
E/AndroidRuntime( 9845): 	at com.eveningoutpost.dexdrip.Models.RollCall.fromJson(RollCall.java:142)
E/AndroidRuntime( 9845): 	at com.eveningoutpost.dexdrip.Models.DesertSync.masterIdReply(DesertSync.java:395)
E/AndroidRuntime( 9845): 	at com.eveningoutpost.dexdrip.UtilityModels.desertsync.DesertComms$QueueHandler.process(DesertComms.java:371)
E/AndroidRuntime( 9845): 	at com.eveningoutpost.dexdrip.UtilityModels.desertsync.DesertComms.httpNext(DesertComms.java:196)
E/AndroidRuntime( 9845): 	at com.eveningoutpost.dexdrip.UtilityModels.desertsync.DesertComms.lambda$runInBackground$0$DesertComms(DesertComms.java:172)
E/AndroidRuntime( 9845): 	at com.eveningoutpost.dexdrip.UtilityModels.desertsync.DesertComms$$Lambda$0.run(Unknown Source)
E/AndroidRuntime( 9845): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime( 9845): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
E/AndroidRuntime( 9845): 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
E/AndroidRuntime( 9845): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)

json was:
E/xxxx    ( 9845): json = Authentication failed - check api-secret
E/xxxx    ( 9845): 
E/xxxx    ( 9845): secret is required 
E/xxxx    ( 9845): supplied secret doesn't match
E/xxxx    ( 9845): Your address: /192.168.3.116
E/xxxx    ( 9845):

**Comment by tzachi-dar** [comment]
https://github.com/NightscoutFoundation/xDrip/pull/613 causes the exceptions to stop happening, still need to debug root cause.

**Comment by Navid200** [comment]
@tzachi-dar Has this been addressed?
Thanks

**Comment by Navid200** [comment]
Closing due to inactivity.
Please reopen if needed.  But, please specify the requirements for closure.
